# Generated by Django 2.2.6 on 2019-11-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
    ]
