# Generated by Django 2.2.6 on 2019-11-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signatures',
            name='reason',
        ),
    ]
